name: Main Scheduler

on:
  schedule:
    - cron: "0 13 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python3.8
        uses: actions/setup-python@v2
        with: 
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytz
      - name: Run Python Script
        run: python my_script.py 